name: yabalash_mobile_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  animate_do: ^3.0.2
  auto_size_text: ^3.0.0
  badges: ^2.0.3 
  bloc: ^8.1.0
  carousel_slider: ^4.1.1
  connectivity_plus: ^3.0.2
  country_picker: ^2.0.18
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_preview: ^1.1.0
  dio: ^4.0.6
  dots_indicator: ^2.1.0
  equatable: ^2.0.5
  extended_image: ^6.3.2
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^8.1.2
  flutter_form_builder: ^7.7.0
  flutter_keyboard_visibility: ^5.4.0
  flutter_native_splash: ^2.2.16
  flutter_screenutil: ^5.6.1
  flutter_styled_toast: ^2.1.3
  flutter_svg: ^1.1.6
  form_builder_validators: ^8.4.0
  get: ^4.6.5
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  map_launcher: ^2.4.0
  onesignal_flutter: ^3.5.0
  overlay_support: ^2.1.0
  path_provider: ^2.0.11
  shimmer: ^2.0.0
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
flutter_native_splash:
  image: assets/images/logo.png
  color: "#ffffff"
  android_gravity: center
  android: true
  ios: true
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/font/Cairo-Regular.ttf
          weight: 400
        - asset: assets/font/Cairo-Medium.ttf
          weight: 500
        - asset: assets/font/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/font/Cairo-Bold.ttf
          weight: 700
